# Generated by Django 5.0 on 2024-07-10 09:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonTracking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('warehouse_name', models.CharField(max_length=1)),
                ('in_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('product_status', models.BooleanField(default=False)),
                ('out_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseB',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseC',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseD',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_status', models.BooleanField(default=False)),
            ],
        ),
    ]
