# Generated by Django 5.0 on 2024-07-12 09:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutTimeTracking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('warehouse_name', models.CharField(max_length=1)),
                ('out_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('product_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='commontracking',
            name='out_time',
        ),
        migrations.AddField(
            model_name='warehouseb',
            name='in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehouseb',
            name='out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehousec',
            name='in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehousec',
            name='out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehoused',
            name='in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehoused',
            name='out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
