# Generated by Django 5.0 on 2024-07-16 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0003_commontracking_out_time_commontracking_product_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouseb',
            name='in_time',
        ),
        migrations.RemoveField(
            model_name='warehouseb',
            name='out_time',
        ),
        migrations.RemoveField(
            model_name='warehousec',
            name='in_time',
        ),
        migrations.RemoveField(
            model_name='warehousec',
            name='out_time',
        ),
        migrations.RemoveField(
            model_name='warehoused',
            name='in_time',
        ),
        migrations.RemoveField(
            model_name='warehoused',
            name='out_time',
        ),
    ]
