# Generated by Django 5.0 on 2024-07-31 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0005_rename_warehouseb_warehouseq_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseZ',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_status', models.BooleanField(default=False)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
