# Generated by Django 5.0 on 2024-08-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0006_warehousez'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_status', models.BooleanField(default=False)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseA0',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_status', models.BooleanField(default=False)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseC',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_status', models.BooleanField(default=False)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseG',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_status', models.BooleanField(default=False)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseH',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_status', models.BooleanField(default=False)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseHR',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_status', models.BooleanField(default=False)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseJ',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_status', models.BooleanField(default=False)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseK',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_status', models.BooleanField(default=False)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseN',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_status', models.BooleanField(default=False)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseR',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_status', models.BooleanField(default=False)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseU',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_status', models.BooleanField(default=False)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseV',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_status', models.BooleanField(default=False)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseX',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_status', models.BooleanField(default=False)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
